// <auto-generated />
using System;
using API_Assessment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Assessment.Migrations
{
    [DbContext(typeof(CodeContextData))]
    [Migration("20250822180202_seeding and automatic date")]
    partial class seedingandautomaticdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Assessment.Models.DirectorClass", b =>
                {
                    b.Property<string>("DirectorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DirectorAge")
                        .HasColumnType("int");

                    b.Property<string>("DirectorEmail")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DirectorExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectorPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DirectorId");

                    b.ToTable("DbDirector");

                    b.HasData(
                        new
                        {
                            DirectorId = "Dir_101",
                            DirectorAge = 45,
                            DirectorEmail = "alexpina@gmail.com",
                            DirectorExperience = "21",
                            DirectorName = "Alex Pina",
                            DirectorPassword = "alexpina"
                        },
                        new
                        {
                            DirectorId = "Dir_102",
                            DirectorAge = 42,
                            DirectorEmail = "baranboodar@gmail.com",
                            DirectorExperience = "17",
                            DirectorName = "Baran Bo Odar",
                            DirectorPassword = "baranboodar"
                        },
                        new
                        {
                            DirectorId = "Dir_103",
                            DirectorAge = 50,
                            DirectorEmail = "sharaddevarajan@gmail.com",
                            DirectorExperience = "27",
                            DirectorName = "Sharad Devarajan",
                            DirectorPassword = "sharaddevarajan"
                        },
                        new
                        {
                            DirectorId = "Dir_104",
                            DirectorAge = 55,
                            DirectorEmail = "christophernolan@gmail.com",
                            DirectorExperience = "32",
                            DirectorName = "Christopher Nolan",
                            DirectorPassword = "christopher"
                        });
                });

            modelBuilder.Entity("API_Assessment.Models.RatingClass", b =>
                {
                    b.Property<string>("RatingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RatingComment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("RatingDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("RatingNo")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserInstanceUserId")
                        .HasColumnType("int");

                    b.Property<string>("WebseriesId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebseriesInstanceWebseriesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RatingId");

                    b.HasIndex("UserInstanceUserId");

                    b.HasIndex("WebseriesInstanceWebseriesId");

                    b.ToTable("DbRating");

                    b.HasData(
                        new
                        {
                            RatingId = "R101",
                            RatingComment = "Amazing!",
                            RatingDate = new DateOnly(2022, 1, 1),
                            RatingNo = 5,
                            UserId = "1",
                            WebseriesId = "Web_101"
                        },
                        new
                        {
                            RatingId = "R102",
                            RatingComment = "Mind-blowing",
                            RatingDate = new DateOnly(2022, 2, 15),
                            RatingNo = 4,
                            UserId = "2",
                            WebseriesId = "Web_102"
                        },
                        new
                        {
                            RatingId = "R103",
                            RatingComment = "Good animation",
                            RatingDate = new DateOnly(2022, 3, 5),
                            RatingNo = 3,
                            UserId = "3",
                            WebseriesId = "Web_103"
                        });
                });

            modelBuilder.Entity("API_Assessment.Models.SeasonsClass", b =>
                {
                    b.Property<string>("SeasonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SeasonPhoto")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("WebseriesId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebseriesInstanceWebseriesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SeasonId");

                    b.HasIndex("WebseriesInstanceWebseriesId");

                    b.ToTable("DbSeason");

                    b.HasData(
                        new
                        {
                            SeasonId = "S101",
                            SeasonPhoto = "moneyheist_s1.jpg",
                            WebseriesId = "Web_101"
                        },
                        new
                        {
                            SeasonId = "S102",
                            SeasonPhoto = "moneyheist_s2.jpg",
                            WebseriesId = "Web_101"
                        },
                        new
                        {
                            SeasonId = "S201",
                            SeasonPhoto = "dark_s1.jpg",
                            WebseriesId = "Web_102"
                        },
                        new
                        {
                            SeasonId = "S301",
                            SeasonPhoto = "hanuman_s1.jpg",
                            WebseriesId = "Web_103"
                        });
                });

            modelBuilder.Entity("API_Assessment.Models.UserClass", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("UserAdult")
                        .HasColumnType("bit");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UserName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserId");

                    b.ToTable("DbUser");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            UserAdult = true,
                            UserEmail = "lalith@gmail.com",
                            UserName = "Lalith",
                            UserPassword = "lalith"
                        },
                        new
                        {
                            UserId = 2,
                            UserAdult = true,
                            UserEmail = "hadiya@gmail.com",
                            UserName = "Hadiya",
                            UserPassword = "hadiya"
                        },
                        new
                        {
                            UserId = 3,
                            UserAdult = false,
                            UserEmail = "Reshni@gmail.com",
                            UserName = "Reshni",
                            UserPassword = "Reshni"
                        });
                });

            modelBuilder.Entity("API_Assessment.Models.WebseriesClass", b =>
                {
                    b.Property<string>("WebseriesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DirectorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectorInstanceDirectorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WebseriesAgerestrictions")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("WebseriesDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("WebseriesTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WebseriesType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WebseriesId");

                    b.HasIndex("DirectorInstanceDirectorId");

                    b.ToTable("DbWebseries");

                    b.HasData(
                        new
                        {
                            WebseriesId = "Web_101",
                            DirectorId = "Dir_101",
                            WebseriesAgerestrictions = "18+",
                            WebseriesDate = new DateOnly(2022, 1, 1),
                            WebseriesTitle = "Money Heist",
                            WebseriesType = "Thriller"
                        },
                        new
                        {
                            WebseriesId = "Web_102",
                            DirectorId = "Dir_102",
                            WebseriesAgerestrictions = "16+",
                            WebseriesDate = new DateOnly(2022, 2, 10),
                            WebseriesTitle = "Dark",
                            WebseriesType = "Sci-Fi"
                        },
                        new
                        {
                            WebseriesId = "Web_103",
                            DirectorId = "Dir_103",
                            WebseriesAgerestrictions = "7+",
                            WebseriesDate = new DateOnly(2022, 3, 15),
                            WebseriesTitle = "The Legend of Hanuman",
                            WebseriesType = "Mythology"
                        });
                });

            modelBuilder.Entity("API_Assessment.Models.RatingClass", b =>
                {
                    b.HasOne("API_Assessment.Models.UserClass", "UserInstance")
                        .WithMany("RatingInstance")
                        .HasForeignKey("UserInstanceUserId");

                    b.HasOne("API_Assessment.Models.WebseriesClass", "WebseriesInstance")
                        .WithMany("RatingInstance")
                        .HasForeignKey("WebseriesInstanceWebseriesId");

                    b.Navigation("UserInstance");

                    b.Navigation("WebseriesInstance");
                });

            modelBuilder.Entity("API_Assessment.Models.SeasonsClass", b =>
                {
                    b.HasOne("API_Assessment.Models.WebseriesClass", "WebseriesInstance")
                        .WithMany("SeasonsInstance")
                        .HasForeignKey("WebseriesInstanceWebseriesId");

                    b.Navigation("WebseriesInstance");
                });

            modelBuilder.Entity("API_Assessment.Models.WebseriesClass", b =>
                {
                    b.HasOne("API_Assessment.Models.DirectorClass", "DirectorInstance")
                        .WithMany("WebseriesInstance")
                        .HasForeignKey("DirectorInstanceDirectorId");

                    b.Navigation("DirectorInstance");
                });

            modelBuilder.Entity("API_Assessment.Models.DirectorClass", b =>
                {
                    b.Navigation("WebseriesInstance");
                });

            modelBuilder.Entity("API_Assessment.Models.UserClass", b =>
                {
                    b.Navigation("RatingInstance");
                });

            modelBuilder.Entity("API_Assessment.Models.WebseriesClass", b =>
                {
                    b.Navigation("RatingInstance");

                    b.Navigation("SeasonsInstance");
                });
#pragma warning restore 612, 618
        }
    }
}
