// <auto-generated />
using API_codefirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_codefirst.Migrations
{
    [DbContext(typeof(CodeContext))]
    partial class CodeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_codefirst.Models.Author", b =>
                {
                    b.Property<int>("authorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("authorId"));

                    b.Property<string>("authorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("phoneNumber")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("authorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            authorId = 1,
                            authorName = "Lalith Kumar",
                            phoneNumber = 8317m
                        },
                        new
                        {
                            authorId = 2,
                            authorName = "Hajeera",
                            phoneNumber = 8315m
                        });
                });

            modelBuilder.Entity("API_codefirst.Models.Book", b =>
                {
                    b.Property<int>("bookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookId"));

                    b.Property<int?>("authorId")
                        .HasColumnType("int");

                    b.Property<string>("bookTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bookId");

                    b.HasIndex("authorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            bookId = 1,
                            authorId = 1,
                            bookTitle = "C# Basics"
                        },
                        new
                        {
                            bookId = 2,
                            authorId = 2,
                            bookTitle = "Advanced EF Core"
                        });
                });

            modelBuilder.Entity("API_codefirst.Models.Book", b =>
                {
                    b.HasOne("API_codefirst.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("authorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("API_codefirst.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
